[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -D CORE_DEBUG_LEVEL=2
    -D CONFIG_ARDUINOTRACE_ENABLE=1

lib_deps = 
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.2
    bblanchon/ArduinoJson @ ^7.0.4
    links2004/WebSockets @ ^2.4.1
    h2zero/NimBLE-Arduino @ ^1.4.1
